### ISSUE TITLE
Any way how to loop transitions?

### ISSUE THREAD

**Issue by fagray** [radical-dreamers/animated-vue#15]
Hi, thanks for the plugin. Is there any way to loop the transitions of the elements? Thanks a lot.

**Comment by srodriki** [comment]
Hey there! As of right now this little implementation does not allow you to loop transitions. I've realized so many features animate.css are really easy to add to the plugin and will do so in the next few days. Truth be told, I've been busy as hell with work for the last few months but will bring forth the new version soon

**Comment by fagray** [comment]
Sorry for late reply. I find my way to resolve my needs. I used `class="animated infinite"` to loop the elements. Anyhow, thanks for the amazing plugin!
