### ISSUE TITLE
can not get it to animate

### ISSUE THREAD

**Issue by mitjarobic** [radical-dreamers/animated-vue#3]
Should there be some css applied on the element?

**Comment by rjulianialtimetrik** [comment]
Hi @mitjarobic 

The plugin itself doesn't load animate.css into your system, as users might have their own build processes. You need to somehow load animate.css (in any way you prefer) so you can see the effects playing out.

For example, if you're using Webpack to build your application, and assuming you installed animate.css using npm, you need to do something like this from your main js file:

```javascript
import 'animate.css/animate.css'
```

you can also statically link animate.css to your application by adding the following line to your main html file's head section:

```html
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/3.5.2/animate.min.css">
</head>
```

Hope the above is useful. If you have any other custom build process, please feel free to share it with me and I will be happy to help.

**Comment by gbdematos** [comment]
I think it's fair to mention this on the readme, I was scratching my head trying to make it work. 😀

**Comment by srodriki** [comment]
@gbdematos you are totally right, and thanks for pointing that out. . I've updated the README so that it mentions how to use it both in ES6+ with a build tool or ES5 directly in any html page.
