### ISSUE TITLE
when i running webpack's bundle process

### ISSUE THREAD

**Issue by zhuxindaba** [radical-dreamers/animated-vue#5]
ERROR in static/js/vendor.min.js?v=d2538ab from UglifyJs
Unexpected token: name (GenericTransition) [./~/animated-vue/src/common/generic-transition/index.js:1,0][static/js/vendor.min.js?v=d2538ab:16,6]

**Comment by admq** [comment]
I got the same error. did you solve it? @zhuxindaba

**Comment by admq** [comment]
I've solved it. Because uglifyjs can't handle ES6, before uglifyjs you need use babel transform it.

- install babel-preset-latest
- include the error file
webpack config file
`{
        test: /\.js$/,
        loader: 'babel-loader',
        include: [resolve('src'), resolve('test'), resolve('node_modules/animated-vue')]
 }`

**Comment by srodriki** [comment]
@admq thanks a lot for your help! I just got time to put my hands on this. You're totally right about the order plugins are included affecting the outcome. 

In my experience, using Vue's project templates is a good way to avoid these issues, but might be some specific template or a custom one are not so careful about that. 

@zhuxindaba I'm really sorry for taking so much time to reply. Can you please confirm if @admq's answer helped you solve the issue?

**Comment by zhuxindaba** [comment]
@admq  your solution isn't a good way, because this doesn't transfrom es6's code to traditional js code, this will lead to browser compatibilities

**Comment by zhuxindaba** [comment]
@admq @srodriki i have solved this problem, thanks a lot
